### PR TITLE
fix(plugins): disable forward delete at end of variable - I374

### LINKED ISSUE #374: Pressing backspace with caret at start of variable allows delete of non variable text
Pressing the backspace key with caret at start of variable allows delete of non variable text.

**To Reproduce**
1. https://cicero-ui.netlify.com
2. Place caret at the end of "Party A"
3. Press backspace to delete all text in the variable except the "
4. Press left arrow key
5. Press backspace
6. The line break outside the variable is removed

**Expected behavior**
Should not be able to delete text outside of variables.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Safari

### PR DESCRIPTION
**Pull request by irmerk**
# Closes #374
Prevent forward deletion at the end of a variable

### Changes
- Check if cursor is at the end of a variable and is attempting to delete forward

### Flags
- Unsure if this addresses @jeromesimeon's [comments](https://github.com/accordproject/cicero-ui/issues/374#issuecomment-621316324)

### Related Issues
- `markdown-editor` PR [#340](https://github.com/accordproject/markdown-editor/pull/340)

### CODE REVIEW

File: src/ContractEditor/plugins/withVariables.js [hunk 1]
```diff
@@ -34,7 +34,15 @@ export const isEditable = (lockText, editor, event) => {
   if (!lockText || !editor.isInsideClause()) return true;
   const { selection } = editor;
   const textLength = Node.get(editor, editor.selection.focus.path).text.length;
+  const atEnd = (editor) => {
+    const textLength = Node.get(editor, editor.selection.focus.path).text.length;
```
Comment (DianaLease) [inline src/ContractEditor/plugins/withVariables.js:38]: `textLength` is already defined on line 36

Comment (irmerk) [reply src/ContractEditor/plugins/withVariables.js:38]: 👀
